POST http://localhost:3001/sign-up HTTP/1.1
Content-Type: application/json

{
    "name": "Usuario",
    "username": "UsuarioTeste5",
    "password": "123456789"
}

###

POST http://localhost:3001/sign-in HTTP/1.1
Content-Type:  application/json

{
    "username": "UsuarioTeste5",
    "password": "123456789"
}